# Generated by Django 2.2.24 on 2021-12-08 17:16

from django.db import migrations


def fill_owner_model(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner = Owner.objects.get(owner=flat.owner,
            owner_pure_phone = flat.owner_pure_phone)
        owner.flat.set([flat])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20211208_1947'),
    ]

    operations = [
        migrations.RunPython(fill_owner_model),
    ]
